- en: The try Block
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: try块
- en: 原文：[https://docs.oracle.com/javase/tutorial/essential/exceptions/try.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/try.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://docs.oracle.com/javase/tutorial/essential/exceptions/try.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/try.html)
- en: 'The first step in constructing an exception handler is to enclose the code
    that might throw an exception within a `try` block. In general, a `try` block
    looks like the following:'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 构建异常处理程序的第一步是将可能会抛出异常的代码放在一个`try`块中。一般来说，一个`try`块看起来像下面这样：
- en: '[PRE0]'
  id: totrans-3
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: The segment in the example labeled `*code*` contains one or more legal lines
    of code that could throw an exception. (The `catch` and `finally` blocks are explained
    in the next two subsections.)
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 在示例中标记为`*code*`的部分包含一个或多个可能会抛出异常的合法代码行。（`catch`和`finally`块将在接下来的两个小节中解释。）
- en: To construct an exception handler for the `writeList` method from the `ListOfNumbers`
    class, enclose the exception-throwing statements of the `writeList` method within
    a `try` block. There is more than one way to do this. You can put each line of
    code that might throw an exception within its own `try` block and provide separate
    exception handlers for each. Or, you can put all the `writeList` code within a
    single `try` block and associate multiple handlers with it. The following listing
    uses one `try` block for the entire method because the code in question is very
    short.
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: 要为`ListOfNumbers`类中的`writeList`方法构建一个异常处理程序，将`writeList`方法中可能会抛出异常的语句放在一个`try`块中。有多种方法可以做到这一点。你可以将每一行可能会抛出异常的代码放在自己的`try`块中，并为每个提供单独的异常处理程序。或者，你可以将所有的`writeList`代码放在一个单独的`try`块中，并为其关联多个处理程序。以下清单使用一个`try`块来处理整个方法，因为相关代码非常简短。
- en: '[PRE1]'
  id: totrans-6
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: If an exception occurs within the `try` block, that exception is handled by
    an exception handler associated with it. To associate an exception handler with
    a `try` block, you must put a `catch` block after it; the next section, [The catch
    Blocks](catch.html), shows you how.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 如果在`try`块中发生异常，该异常将由与之关联的异常处理程序处理。要为`try`块关联一个异常处理程序，必须在其后放置一个`catch`块；下一节，[catch块](catch.html)，将向你展示如何做到这一点。
